<!DOCTYPE HTML>
<html lang="en-US">
<head>
    <link rel="stylesheet" href="<? $this->baseUrl('bootstrap/css/bootstrap.css') ?>" />
    <link rel="stylesheet" href="<? $this->baseUrl('bootstrap/css/bootstrap-responsive.css') ?>" />
    <script type="text/javascript" src="<? $this->baseUrl('bootstrap/js/bootstrap.js') ?>" />
    <meta charset="UTF-8">
    <title></title>
</head>
<body>
    <header class="container-fluid">
        <div class="navbar">
            
        </div>
    </header>
    <article class="container-fluid">
        
    </article>
</body>
</html>